kind: pipeline
type: kubernetes
name: pi-cluster

steps:
- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: jtbarclay/lastfm-ytmusic-playlist
    tags: ["${DRONE_COMMIT_SHA:0:7}", "latest"]

- name: deploy
  image: jtbarclay/drone-kubernetes:latest
  settings:
    kubernetes_server:
      from_secret: k3s_server
    kubernetes_cert:
      from_secret: k3s_cert
    kubernetes_token:
      from_secret: k3s_token
    deployment: lastfm-ytmusic-playlist
    repo: jtbarclay/lastfm-ytmusic-playlist
    container: lastfm-ytmusic-playlist
    namespace: lastfm-ytmusic-playlist
    tag:                 
      - ${DRONE_COMMIT_SHA:0:7}