kind: pipeline
type: kubernetes
name: pi-cluster

steps:
- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: jtbarclay/lastfm-ytmusic-playlist
    tags: ["${DRONE_COMMIT_SHA:0:7}", "latest"]