apiVersion: v1
kind: ServiceAccount
metadata:
  name: lastfm-ytmusic-playlist
  namespace: lastfm-ytmusic-playlist

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lastfm-ytmusic-playlist
  namespace: lastfm-ytmusic-playlist
rules:
  - apiGroups: ["batch"]
    resources: ["*"]
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lastfm-ytmusic-playlist
  namespace: lastfm-ytmusic-playlist
subjects:
  - kind: ServiceAccount
    name: lastfm-ytmusic-playlist
    namespace: lastfm-ytmusic-playlist
roleRef:
  kind: Role
  name: lastfm-ytmusic-playlist
  apiGroup: rbac.authorization.k8s.io